// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoRHFs0naTSfS4lGNI7E1Al9XmLqeWsKo',
    appId: '1:594890025186:web:851a374f18c02248e8d6bb',
    messagingSenderId: '594890025186',
    projectId: 'career-gem',
    authDomain: 'career-gem.firebaseapp.com',
    storageBucket: 'career-gem.firebasestorage.app',
    measurementId: 'G-MPKM6DFP1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2q6n88HkIeblTV1VqvQ-561cBHJd0H04',
    appId: '1:594890025186:android:748a34da28e23c1ce8d6bb',
    messagingSenderId: '594890025186',
    projectId: 'career-gem',
    storageBucket: 'career-gem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp03ENIBKGOyieq1xPdWI7QIhD5l_StD4',
    appId: '1:594890025186:ios:f684a099e1f3985ee8d6bb',
    messagingSenderId: '594890025186',
    projectId: 'career-gem',
    storageBucket: 'career-gem.firebasestorage.app',
    androidClientId: '594890025186-1mr1t8kb96utdkhhskp26co614a8im2j.apps.googleusercontent.com',
    iosClientId: '594890025186-kjbhgm608ikhn3k47fcc3r419t60iptm.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerGem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp03ENIBKGOyieq1xPdWI7QIhD5l_StD4',
    appId: '1:594890025186:ios:f684a099e1f3985ee8d6bb',
    messagingSenderId: '594890025186',
    projectId: 'career-gem',
    storageBucket: 'career-gem.firebasestorage.app',
    androidClientId: '594890025186-1mr1t8kb96utdkhhskp26co614a8im2j.apps.googleusercontent.com',
    iosClientId: '594890025186-kjbhgm608ikhn3k47fcc3r419t60iptm.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerGem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoRHFs0naTSfS4lGNI7E1Al9XmLqeWsKo',
    appId: '1:594890025186:web:ab5828edc1355a2de8d6bb',
    messagingSenderId: '594890025186',
    projectId: 'career-gem',
    authDomain: 'career-gem.firebaseapp.com',
    storageBucket: 'career-gem.firebasestorage.app',
    measurementId: 'G-CB8FR9C8K5',
  );

}